blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/julianoczkowski/modus-vue-app/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Vulnerability
    url: mailto:julian_oczkowski@trimble.com
    about: Report security vulnerabilities privately via email
  - name: 📚 Modus Web Components Documentation
    url: https://trimble-oss.github.io/modus-wc-2.0/main/
    about: Official Modus Web Components documentation and examples
  - name: 🎨 Modus Figma MCP Integration
    url: https://trimble-oss.github.io/modus-wc-2.0/main/?path=/docs/documentation-modus-figma-mcp-integration-guide--docs
    about: Learn about Figma to code integration with AI assistance
