name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Modus Vue Boilerplate
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: ["julianoczkowski"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following steps
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature aligns with the boilerplate's scope (Vue 3 + Modus 2 integration)
          required: true
        - label: I have considered if this should be a separate package/plugin instead
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or use case this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution for this feature
      placeholder: Describe what you'd like to see implemented...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions you've considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - Component Examples
        - Development Tools
        - Build/Deployment
        - Documentation
        - Performance
        - Accessibility
        - Testing
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Related Components
      description: Which components or areas would this feature affect?
      options:
        - label: Modus Web Components integration
        - label: Vue component architecture
        - label: Icon system
        - label: Theme system
        - label: Color system
        - label: TypeScript definitions
        - label: Build configuration
        - label: Development rules
        - label: MCP servers
        - label: Documentation

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: Share any implementation ideas or technical approaches...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        ```vue
        // Example usage
        <template>
          <!-- Your example here -->
        </template>
        ```

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes
        - label: This feature can be implemented without breaking changes
        - label: I'm not sure about breaking changes

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature provide to users?
      placeholder: List the benefits this feature would provide...

  - type: textarea
    id: drawbacks
    attributes:
      label: Potential Drawbacks
      description: Are there any potential drawbacks or concerns with this feature?
      placeholder: List any potential drawbacks or concerns...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide design/UX input
        - label: I prefer to let others implement this

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information that might be helpful...
